# https://taskfile.dev

version: "3"

includes:
  yatlc:
    taskfile: yatlc/yatlc.tasks.yml
    dir: yatlc
  poc:
    taskfile: poc/poc.tasks.yml
    dir: poc

tasks:
  default:
    deps:
      - ci

  ci:
    run: once
    deps:
      - yatlc:ci

  poc:
    run: once
    deps:
      - poc:run
